### ISSUE TITLE
Turn On the Torch

### ISSUE THREAD

**Issue by jakama** [Moonware/cordova-cameraplus#2]
Hello,

It is possible turn on the torch during the camera capturing?

Thanks!

**Comment by w3t** [comment]
It is available in https://github.com/Moonware/cordova-cameraserver

You can however copy the code from this project to add this feature to cameraplus if you need it.

**Comment by jakama** [comment]
@w3t, like we say in Spain: Ole! Ole! Ole! Thanks a lot. Solved!
